### ISSUE TITLE
Different behavior between  1.9.3 and 1.10.0-beta2

### ISSUE THREAD

**Issue by j-fu** [JuliaPluto/HypertextLiteral.jl#35]
Not sure if it is due to HypertextLiteral, AbstractPlutoDingetjes, or Julia.
Please see https://github.com/JuliaPluto/AbstractPlutoDingetjes.jl/issues/12

**Comment by clarkevans** [comment]
Could you post a minimum working example, e.g. something that works in 1.9.3 and fails in 1.10.0-beta2 ?

**Comment by j-fu** [comment]
Forgot to copy it over here. [here](https://gist.github.com/j-fu/e13e33f03b260ad44ab36b47c7101b32) it is.

**Comment by fonsp** [comment]
Fixed by #36
